"""Pin the installed dependency closure; run after installing backend[dev]."""

from importlib.metadata import distribution
from pathlib import Path

from packaging.requirements import Requirement
from packaging.utils import canonicalize_name

ROOT = Path(__file__).resolve().parents[1]


def lock(roots: list[str], filename: str) -> None:
    pending = list(roots)
    versions: dict[str, str] = {}
    while pending:
        name = canonicalize_name(pending.pop())
        if name in versions:
            continue
        installed = distribution(name)
        versions[name] = installed.version
        for text in installed.requires or []:
            requirement = Requirement(text)
            if requirement.marker is None or requirement.marker.evaluate({"extra": ""}):
                pending.append(requirement.name)
    lines = ["# Generated by scripts/lock_dependencies.py for Python 3.12."]
    lines.extend(f"{name}=={version}" for name, version in sorted(versions.items()))
    (ROOT / "backend" / filename).write_text("\n".join(lines) + "\n", encoding="utf-8")


runtime = ["fastapi", "uvicorn", "python-dotenv"]
lock(runtime, "requirements.lock")
lock(runtime + ["pytest", "httpx", "ruff", "packaging"], "requirements-dev.lock")
